apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-stack.fullname" . }}-gateway-config
data:
  relay.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    exporters:
      influxdb:
        endpoint: http://{{ include "otel-stack.fullname" . }}-influxdb:8086
        token: {{ .Values.influxdb.adminToken | quote }}
        organization: {{ .Values.influxdb.org | quote }}
        bucket: {{ .Values.influxdb.bucket | quote }}
      logging:
        verbosity: detailed
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [influxdb, logging]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
