apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-stack.fullname" . }}-grafana-provisioning
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        url: http://{{ include "otel-stack.fullname" . }}-influxdb:8086
        jsonData:
          version: Flux
          organization: {{ .Values.influxdb.org | quote }}
          defaultBucket: {{ .Values.influxdb.bucket | quote }}
        secureJsonData:
          token: {{ .Values.influxdb.adminToken | quote }}
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'Default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/provisioning/dashboards
  dashboard.json: |
{{ .Files.Get "dashboards/dashboard.json" | indent 4 }}
